-- PATIENT
CREATE TABLE patient (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(200) NOT NULL,
  date_of_birth DATE,
  gender VARCHAR2(10),
  contact_info VARCHAR2(200),
  allergies VARCHAR2(1000),
  medical_conditions VARCHAR2(1000)
);

-- DOCTOR
CREATE TABLE doctor (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(200) NOT NULL,
  specialization VARCHAR2(100),
  contact_info VARCHAR2(200)
);

-- MEDICINE
CREATE TABLE medicine (
  med_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  med_name VARCHAR2(200) NOT NULL,
  composition VARCHAR2(500),
  category VARCHAR2(100),
  dosage_form VARCHAR2(50),
  strength VARCHAR2(50),
  manufacturer VARCHAR2(200),
  is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);

-- PRESCRIPTION (header)
CREATE TABLE prescription (
  pres_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER,
  pres_date DATE DEFAULT SYSDATE,
  remarks VARCHAR2(500),
  CONSTRAINT fk_pres_patient FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
  CONSTRAINT fk_pres_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
);

-- PRESCRIPTION_DETAIL (lines)
CREATE TABLE prescription_detail (
  detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pres_id NUMBER NOT NULL,
  med_id NUMBER NOT NULL,
  dose VARCHAR2(50),
  frequency VARCHAR2(50),
  duration_days NUMBER CHECK (duration_days >= 0),
  CONSTRAINT fk_pd_pres FOREIGN KEY (pres_id) REFERENCES prescription(pres_id),
  CONSTRAINT fk_pd_med FOREIGN KEY (med_id) REFERENCES medicine(med_id)
);

-- INTERACTION (canonical med1 < med2 enforced via trigger or application)
CREATE TABLE interaction (
  interaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  med1_id NUMBER NOT NULL,
  med2_id NUMBER NOT NULL,
  severity_level VARCHAR2(20) CHECK (severity_level IN ('Minor','Moderate','Major')),
  effect_description VARCHAR2(1000),
  management_advice VARCHAR2(1000),
  CONSTRAINT fk_int_med1 FOREIGN KEY (med1_id) REFERENCES medicine(med_id),
  CONSTRAINT fk_int_med2 FOREIGN KEY (med2_id) REFERENCES medicine(med_id),
  CONSTRAINT ux_medpair UNIQUE (med1_id, med2_id)
);

-- ALERT_LOG
CREATE TABLE alert_log (
  alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER,
  pres_id NUMBER,
  med1_id NUMBER,
  med2_id NUMBER,
  alert_date TIMESTAMP DEFAULT SYSTIMESTAMP,
  severity_level VARCHAR2(20),
  message VARCHAR2(1000),
  handled_by NUMBER,
  CONSTRAINT fk_alert_patient FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
  CONSTRAINT fk_alert_pres FOREIGN KEY (pres_id) REFERENCES prescription(pres_id),
  CONSTRAINT fk_alert_med1 FOREIGN KEY (med1_id) REFERENCES medicine(med_id),
  CONSTRAINT fk_alert_med2 FOREIGN KEY (med2_id) REFERENCES medicine(med_id),
  CONSTRAINT fk_alert_handledby FOREIGN KEY (handled_by) REFERENCES doctor(doctor_id)
);

--creating public_holiday table
DROP TABLE public_holidays  CASCADE CONSTRAINTS;

CREATE TABLE public_holidays (
  holiday_date DATE PRIMARY KEY,
  description VARCHAR2(30)
);

-- Indexes for performance
CREATE INDEX ix_pres_patient ON prescription(patient_id);
CREATE INDEX ix_pd_pres ON prescription_detail(pres_id);
CREATE INDEX ix_pd_med ON prescription_detail(med_id);
CREATE INDEX ix_int_meds ON interaction(med1_id, med2_id);
CREATE INDEX ix_alert_date ON alert_log(alert_date);
CREATE INDEX ix_alert_meds ON alert_log(med1_id, med2_id);

COMMIT;